--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 17.1

-- Started on 2025-01-30 21:35:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 20 (class 2615 OID 2200)
-- Name: test; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA   test;


ALTER SCHEMA test OWNER TO pg_database_owner;

--
-- TOC entry 3946 (class 0 OID 0)
-- Dependencies: 20
-- Name: SCHEMA test; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA test IS 'standard test schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 284 (class 1259 OID 29631)
-- Name: tbl_article; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE tbl_article (
    id bigint NOT NULL,
    article_nominal bigint,
    article_min bigint,
    article_max bigint,
    number_control integer,
    is_exist boolean,
    user_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    article_name character varying,
    customer_id bigint
);


ALTER TABLE tbl_article OWNER TO postgres;

--
-- TOC entry 285 (class 1259 OID 29638)
-- Name: tbl_article_id_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test.tbl_article ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME test.tbl_article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 286 (class 1259 OID 29639)
-- Name: tbl_article_max; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.tbl_article_max (
    id bigint NOT NULL,
    length double precision,
    inside_diameter double precision,
    outside_diameter double precision,
    flat_crush double precision,
    h20 double precision,
    is_exist boolean,
    user_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE test.tbl_article_max OWNER TO postgres;

--
-- TOC entry 287 (class 1259 OID 29644)
-- Name: tbl_article_max_id_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test.tbl_article_max ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME test.tbl_article_max_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 288 (class 1259 OID 29645)
-- Name: tbl_article_min; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.tbl_article_min (
    id bigint NOT NULL,
    length double precision,
    inside_diameter double precision,
    outside_diameter double precision,
    flat_crush double precision,
    h20 double precision,
    is_exist boolean,
    user_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE test.tbl_article_min OWNER TO postgres;

--
-- TOC entry 289 (class 1259 OID 29650)
-- Name: tbl_article_min_id_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test.tbl_article_min ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME test.tbl_article_min_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 290 (class 1259 OID 29651)
-- Name: tbl_article_nominal; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.tbl_article_nominal (
    id bigint NOT NULL,
    length double precision,
    inside_diameter double precision,
    outside_diameter double precision,
    flat_crush double precision,
    h20 double precision,
    is_exist boolean,
    user_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE test.tbl_article_nominal OWNER TO postgres;

--
-- TOC entry 291 (class 1259 OID 29656)
-- Name: tbl_article_nominal_id_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test.tbl_article_nominal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME test.tbl_article_nominal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 292 (class 1259 OID 29657)
-- Name: tbl_assignee_history; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.tbl_assignee_history (
    id bigint NOT NULL,
    order_form_id bigint,
    created_date timestamp with time zone,
    is_assigned boolean,
    is_exist boolean,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    user_id uuid
);


ALTER TABLE test.tbl_assignee_history OWNER TO postgres;

--
-- TOC entry 293 (class 1259 OID 29662)
-- Name: tbl_assignee_history_id_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test.tbl_assignee_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME test.tbl_assignee_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 294 (class 1259 OID 29663)
-- Name: tbl_customer; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.tbl_customer (
    id bigint NOT NULL,
    first_name text,
    middle_name text,
    last_name text,
    email text,
    is_exist boolean,
    user_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    company_name text
);


ALTER TABLE test.tbl_customer OWNER TO postgres;

--
-- TOC entry 295 (class 1259 OID 29670)
-- Name: tbl_customer_id_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test.tbl_customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME test.tbl_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 296 (class 1259 OID 29671)
-- Name: tbl_laboratory; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.tbl_laboratory (
    id bigint NOT NULL,
    order_form_id bigint,
    flat_crush double precision,
    h20 double precision,
    is_exist boolean,
    user_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE test.tbl_laboratory OWNER TO postgres;

--
-- TOC entry 297 (class 1259 OID 29676)
-- Name: tbl_measurement; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.tbl_measurement (
    id bigint NOT NULL,
    order_form_id bigint,
    length double precision,
    inside_diameter double precision,
    outside_diameter double precision,
    flat_crush double precision,
    h20 double precision,
    radial double precision,
    number_control integer,
    remarks text,
    is_exist boolean,
    user_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    pallete_count integer
);


ALTER TABLE test.tbl_measurement OWNER TO postgres;

--
-- TOC entry 298 (class 1259 OID 29683)
-- Name: tbl_measurement_history; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.tbl_measurement_history (
    id bigint NOT NULL,
    order_form_id bigint,
    length double precision,
    inside_diameter double precision,
    outside_diameter double precision,
    flat_crush double precision,
    h20 double precision,
    radial double precision,
    number_control bigint,
    remarks text,
    user_id uuid,
    is_exist boolean,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone
);


ALTER TABLE test.tbl_measurement_history OWNER TO postgres;

--
-- TOC entry 299 (class 1259 OID 29689)
-- Name: tbl_measurement_id_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test.tbl_measurement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME test.tbl_measurement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 300 (class 1259 OID 29690)
-- Name: tbl_orders_form; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.tbl_orders_form (
    id bigint NOT NULL,
    customer_id bigint,
    article_id bigint,
    assignee uuid,
    pallete_count bigint,
    is_assigned boolean,
    is_exist boolean,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    product_name text,
    order_fabrication_control text,
    entry_date_time timestamp with time zone,
    exit_date_time timestamp with time zone
);


ALTER TABLE test.tbl_orders_form OWNER TO postgres;

--
-- TOC entry 301 (class 1259 OID 29697)
-- Name: tbl_orders_form_id_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test.tbl_orders_form ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME test.tbl_orders_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 302 (class 1259 OID 29698)
-- Name: tbl_production; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.tbl_production (
    id bigint NOT NULL,
    order_form_id bigint,
    entry_date_time timestamp with time zone,
    exit_date_time timestamp with time zone,
    is_exist boolean,
    user_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE test.tbl_production OWNER TO postgres;

--
-- TOC entry 303 (class 1259 OID 29703)
-- Name: tbl_production_id_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test.tbl_production ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME test.tbl_production_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 304 (class 1259 OID 29704)
-- Name: tbl_proofing; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.tbl_proofing (
    id bigint NOT NULL,
    order_form_id bigint,
    entry_date_time timestamp with time zone,
    exit_date_time timestamp with time zone,
    num_pallets bigint,
    program_name text,
    is_exist boolean,
    user_id uuid,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE test.tbl_proofing OWNER TO postgres;

--
-- TOC entry 305 (class 1259 OID 29711)
-- Name: tbl_proofing_id_seq; Type: SEQUENCE; Schema: test; Owner: postgres
--

ALTER TABLE test.tbl_proofing ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME test.tbl_proofing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 306 (class 1259 OID 29712)
-- Name: tbl_users; Type: TABLE; Schema: test; Owner: postgres
--

CREATE TABLE test.tbl_users (
    uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    first_name text,
    middle_name text,
    last_name text,
    suffix text,
    role text,
    is_exist boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    email text,
    is_verified boolean DEFAULT false,
    code text,
    code_expiration timestamp with time zone
);


ALTER TABLE test.tbl_users OWNER TO postgres;

--
-- TOC entry 3743 (class 2606 OID 29825)
-- Name: tbl_article_max tbl_article_max_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_article_max
    ADD CONSTRAINT tbl_article_max_pkey PRIMARY KEY (id);


--
-- TOC entry 3745 (class 2606 OID 29827)
-- Name: tbl_article_min tbl_article_min_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_article_min
    ADD CONSTRAINT tbl_article_min_pkey PRIMARY KEY (id);


--
-- TOC entry 3747 (class 2606 OID 29829)
-- Name: tbl_article_nominal tbl_article_nominal_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_article_nominal
    ADD CONSTRAINT tbl_article_nominal_pkey PRIMARY KEY (id);


--
-- TOC entry 3741 (class 2606 OID 29831)
-- Name: tbl_article tbl_article_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_article
    ADD CONSTRAINT tbl_article_pkey PRIMARY KEY (id);


--
-- TOC entry 3749 (class 2606 OID 29833)
-- Name: tbl_assignee_history tbl_assignee_history_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_assignee_history
    ADD CONSTRAINT tbl_assignee_history_pkey PRIMARY KEY (id);


--
-- TOC entry 3751 (class 2606 OID 29835)
-- Name: tbl_customer tbl_customer_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_customer
    ADD CONSTRAINT tbl_customer_pkey PRIMARY KEY (id);


--
-- TOC entry 3753 (class 2606 OID 29837)
-- Name: tbl_laboratory tbl_laboratory_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_laboratory
    ADD CONSTRAINT tbl_laboratory_pkey PRIMARY KEY (id);


--
-- TOC entry 3757 (class 2606 OID 29839)
-- Name: tbl_measurement_history tbl_measurement_history_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_measurement_history
    ADD CONSTRAINT tbl_measurement_history_pkey PRIMARY KEY (id);


--
-- TOC entry 3755 (class 2606 OID 29841)
-- Name: tbl_measurement tbl_measurement_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_measurement
    ADD CONSTRAINT tbl_measurement_pkey PRIMARY KEY (id);


--
-- TOC entry 3759 (class 2606 OID 29843)
-- Name: tbl_orders_form tbl_orders_form_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_orders_form
    ADD CONSTRAINT tbl_orders_form_pkey PRIMARY KEY (id);


--
-- TOC entry 3761 (class 2606 OID 29845)
-- Name: tbl_production tbl_production_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_production
    ADD CONSTRAINT tbl_production_pkey PRIMARY KEY (id);


--
-- TOC entry 3763 (class 2606 OID 29847)
-- Name: tbl_proofing tbl_proofing_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_proofing
    ADD CONSTRAINT tbl_proofing_pkey PRIMARY KEY (id);


--
-- TOC entry 3765 (class 2606 OID 29849)
-- Name: tbl_users tbl_users_pkey; Type: CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_users
    ADD CONSTRAINT tbl_users_pkey PRIMARY KEY (uuid);


--
-- TOC entry 3779 (class 2606 OID 29970)
-- Name: tbl_measurement fk_order_form; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_measurement
    ADD CONSTRAINT fk_order_form FOREIGN KEY (order_form_id) REFERENCES test.tbl_orders_form(id) ON DELETE CASCADE;


--
-- TOC entry 3766 (class 2606 OID 29975)
-- Name: tbl_article tbl_article_article_max_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_article
    ADD CONSTRAINT tbl_article_article_max_fkey FOREIGN KEY (article_max) REFERENCES test.tbl_article_max(id);


--
-- TOC entry 3767 (class 2606 OID 29980)
-- Name: tbl_article tbl_article_article_min_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_article
    ADD CONSTRAINT tbl_article_article_min_fkey FOREIGN KEY (article_min) REFERENCES test.tbl_article_min(id);


--
-- TOC entry 3768 (class 2606 OID 29985)
-- Name: tbl_article tbl_article_article_nominal_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_article
    ADD CONSTRAINT tbl_article_article_nominal_fkey FOREIGN KEY (article_nominal) REFERENCES test.tbl_article_nominal(id);


--
-- TOC entry 3769 (class 2606 OID 29990)
-- Name: tbl_article tbl_article_customer_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_article
    ADD CONSTRAINT tbl_article_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES test.tbl_customer(id);


--
-- TOC entry 3771 (class 2606 OID 29995)
-- Name: tbl_article_max tbl_article_max_user_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_article_max
    ADD CONSTRAINT tbl_article_max_user_id_fkey FOREIGN KEY (user_id) REFERENCES test.tbl_users(uuid);


--
-- TOC entry 3772 (class 2606 OID 30000)
-- Name: tbl_article_min tbl_article_min_user_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_article_min
    ADD CONSTRAINT tbl_article_min_user_id_fkey FOREIGN KEY (user_id) REFERENCES test.tbl_users(uuid);


--
-- TOC entry 3773 (class 2606 OID 30005)
-- Name: tbl_article_nominal tbl_article_nominal_user_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_article_nominal
    ADD CONSTRAINT tbl_article_nominal_user_id_fkey FOREIGN KEY (user_id) REFERENCES test.tbl_users(uuid);


--
-- TOC entry 3770 (class 2606 OID 30010)
-- Name: tbl_article tbl_article_user_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_article
    ADD CONSTRAINT tbl_article_user_id_fkey FOREIGN KEY (user_id) REFERENCES test.tbl_users(uuid);


--
-- TOC entry 3774 (class 2606 OID 30015)
-- Name: tbl_assignee_history tbl_assignee_history_order_form_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_assignee_history
    ADD CONSTRAINT tbl_assignee_history_order_form_id_fkey FOREIGN KEY (order_form_id) REFERENCES test.tbl_orders_form(id);


--
-- TOC entry 3775 (class 2606 OID 30020)
-- Name: tbl_assignee_history tbl_assignee_history_user_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_assignee_history
    ADD CONSTRAINT tbl_assignee_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES test.tbl_users(uuid);


--
-- TOC entry 3776 (class 2606 OID 30025)
-- Name: tbl_customer tbl_customer_user_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_customer
    ADD CONSTRAINT tbl_customer_user_id_fkey FOREIGN KEY (user_id) REFERENCES test.tbl_users(uuid);


--
-- TOC entry 3777 (class 2606 OID 30030)
-- Name: tbl_laboratory tbl_laboratory_order_form_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_laboratory
    ADD CONSTRAINT tbl_laboratory_order_form_id_fkey FOREIGN KEY (order_form_id) REFERENCES test.tbl_orders_form(id);


--
-- TOC entry 3778 (class 2606 OID 30035)
-- Name: tbl_laboratory tbl_laboratory_user_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_laboratory
    ADD CONSTRAINT tbl_laboratory_user_id_fkey FOREIGN KEY (user_id) REFERENCES test.tbl_users(uuid);


--
-- TOC entry 3782 (class 2606 OID 30040)
-- Name: tbl_measurement_history tbl_measurement_history_order_form_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_measurement_history
    ADD CONSTRAINT tbl_measurement_history_order_form_id_fkey FOREIGN KEY (order_form_id) REFERENCES test.tbl_orders_form(id);


--
-- TOC entry 3783 (class 2606 OID 30045)
-- Name: tbl_measurement_history tbl_measurement_history_user_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_measurement_history
    ADD CONSTRAINT tbl_measurement_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES test.tbl_users(uuid);


--
-- TOC entry 3780 (class 2606 OID 30050)
-- Name: tbl_measurement tbl_measurement_order_form_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_measurement
    ADD CONSTRAINT tbl_measurement_order_form_id_fkey FOREIGN KEY (order_form_id) REFERENCES test.tbl_orders_form(id);


--
-- TOC entry 3781 (class 2606 OID 30055)
-- Name: tbl_measurement tbl_measurement_user_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_measurement
    ADD CONSTRAINT tbl_measurement_user_id_fkey FOREIGN KEY (user_id) REFERENCES test.tbl_users(uuid);


--
-- TOC entry 3784 (class 2606 OID 30060)
-- Name: tbl_orders_form tbl_orders_form_article_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_orders_form
    ADD CONSTRAINT tbl_orders_form_article_id_fkey FOREIGN KEY (article_id) REFERENCES test.tbl_article(id);


--
-- TOC entry 3785 (class 2606 OID 30065)
-- Name: tbl_orders_form tbl_orders_form_assignee_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_orders_form
    ADD CONSTRAINT tbl_orders_form_assignee_fkey FOREIGN KEY (assignee) REFERENCES test.tbl_users(uuid);


--
-- TOC entry 3786 (class 2606 OID 30070)
-- Name: tbl_orders_form tbl_orders_form_customer_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_orders_form
    ADD CONSTRAINT tbl_orders_form_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES test.tbl_customer(id);


--
-- TOC entry 3787 (class 2606 OID 30075)
-- Name: tbl_production tbl_production_order_form_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_production
    ADD CONSTRAINT tbl_production_order_form_id_fkey FOREIGN KEY (order_form_id) REFERENCES test.tbl_orders_form(id);


--
-- TOC entry 3788 (class 2606 OID 30080)
-- Name: tbl_production tbl_production_user_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_production
    ADD CONSTRAINT tbl_production_user_id_fkey FOREIGN KEY (user_id) REFERENCES test.tbl_users(uuid);


--
-- TOC entry 3789 (class 2606 OID 30085)
-- Name: tbl_proofing tbl_proofing_order_form_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_proofing
    ADD CONSTRAINT tbl_proofing_order_form_id_fkey FOREIGN KEY (order_form_id) REFERENCES test.tbl_orders_form(id);


--
-- TOC entry 3790 (class 2606 OID 30090)
-- Name: tbl_proofing tbl_proofing_user_id_fkey; Type: FK CONSTRAINT; Schema: test; Owner: postgres
--

ALTER TABLE ONLY test.tbl_proofing
    ADD CONSTRAINT tbl_proofing_user_id_fkey FOREIGN KEY (user_id) REFERENCES test.tbl_users(uuid);


--
-- TOC entry 3947 (class 0 OID 0)
-- Dependencies: 20
-- Name: SCHEMA test; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA test TO postgres;
GRANT USAGE ON SCHEMA test TO anon;
GRANT USAGE ON SCHEMA test TO authenticated;
GRANT USAGE ON SCHEMA test TO service_role;


--
-- TOC entry 3948 (class 0 OID 0)
-- Dependencies: 284
-- Name: TABLE tbl_article; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_article TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_article TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_article TO service_role;


--
-- TOC entry 3949 (class 0 OID 0)
-- Dependencies: 285
-- Name: SEQUENCE tbl_article_id_seq; Type: ACL; Schema: test; Owner: postgres
--

GRANT ALL ON SEQUENCE test.tbl_article_id_seq TO anon;
GRANT ALL ON SEQUENCE test.tbl_article_id_seq TO authenticated;
GRANT ALL ON SEQUENCE test.tbl_article_id_seq TO service_role;


--
-- TOC entry 3950 (class 0 OID 0)
-- Dependencies: 286
-- Name: TABLE tbl_article_max; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_article_max TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_article_max TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_article_max TO service_role;


--
-- TOC entry 3951 (class 0 OID 0)
-- Dependencies: 287
-- Name: SEQUENCE tbl_article_max_id_seq; Type: ACL; Schema: test; Owner: postgres
--

GRANT ALL ON SEQUENCE test.tbl_article_max_id_seq TO anon;
GRANT ALL ON SEQUENCE test.tbl_article_max_id_seq TO authenticated;
GRANT ALL ON SEQUENCE test.tbl_article_max_id_seq TO service_role;


--
-- TOC entry 3952 (class 0 OID 0)
-- Dependencies: 288
-- Name: TABLE tbl_article_min; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_article_min TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_article_min TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_article_min TO service_role;


--
-- TOC entry 3953 (class 0 OID 0)
-- Dependencies: 289
-- Name: SEQUENCE tbl_article_min_id_seq; Type: ACL; Schema: test; Owner: postgres
--

GRANT ALL ON SEQUENCE test.tbl_article_min_id_seq TO anon;
GRANT ALL ON SEQUENCE test.tbl_article_min_id_seq TO authenticated;
GRANT ALL ON SEQUENCE test.tbl_article_min_id_seq TO service_role;


--
-- TOC entry 3954 (class 0 OID 0)
-- Dependencies: 290
-- Name: TABLE tbl_article_nominal; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_article_nominal TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_article_nominal TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_article_nominal TO service_role;


--
-- TOC entry 3955 (class 0 OID 0)
-- Dependencies: 291
-- Name: SEQUENCE tbl_article_nominal_id_seq; Type: ACL; Schema: test; Owner: postgres
--

GRANT ALL ON SEQUENCE test.tbl_article_nominal_id_seq TO anon;
GRANT ALL ON SEQUENCE test.tbl_article_nominal_id_seq TO authenticated;
GRANT ALL ON SEQUENCE test.tbl_article_nominal_id_seq TO service_role;


--
-- TOC entry 3956 (class 0 OID 0)
-- Dependencies: 292
-- Name: TABLE tbl_assignee_history; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_assignee_history TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_assignee_history TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_assignee_history TO service_role;


--
-- TOC entry 3957 (class 0 OID 0)
-- Dependencies: 293
-- Name: SEQUENCE tbl_assignee_history_id_seq; Type: ACL; Schema: test; Owner: postgres
--

GRANT ALL ON SEQUENCE test.tbl_assignee_history_id_seq TO anon;
GRANT ALL ON SEQUENCE test.tbl_assignee_history_id_seq TO authenticated;
GRANT ALL ON SEQUENCE test.tbl_assignee_history_id_seq TO service_role;


--
-- TOC entry 3958 (class 0 OID 0)
-- Dependencies: 294
-- Name: TABLE tbl_customer; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_customer TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_customer TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_customer TO service_role;


--
-- TOC entry 3959 (class 0 OID 0)
-- Dependencies: 295
-- Name: SEQUENCE tbl_customer_id_seq; Type: ACL; Schema: test; Owner: postgres
--

GRANT ALL ON SEQUENCE test.tbl_customer_id_seq TO anon;
GRANT ALL ON SEQUENCE test.tbl_customer_id_seq TO authenticated;
GRANT ALL ON SEQUENCE test.tbl_customer_id_seq TO service_role;


--
-- TOC entry 3960 (class 0 OID 0)
-- Dependencies: 296
-- Name: TABLE tbl_laboratory; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_laboratory TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_laboratory TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_laboratory TO service_role;


--
-- TOC entry 3961 (class 0 OID 0)
-- Dependencies: 297
-- Name: TABLE tbl_measurement; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_measurement TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_measurement TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_measurement TO service_role;


--
-- TOC entry 3962 (class 0 OID 0)
-- Dependencies: 298
-- Name: TABLE tbl_measurement_history; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_measurement_history TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_measurement_history TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_measurement_history TO service_role;


--
-- TOC entry 3963 (class 0 OID 0)
-- Dependencies: 299
-- Name: SEQUENCE tbl_measurement_id_seq; Type: ACL; Schema: test; Owner: postgres
--

GRANT ALL ON SEQUENCE test.tbl_measurement_id_seq TO anon;
GRANT ALL ON SEQUENCE test.tbl_measurement_id_seq TO authenticated;
GRANT ALL ON SEQUENCE test.tbl_measurement_id_seq TO service_role;


--
-- TOC entry 3964 (class 0 OID 0)
-- Dependencies: 300
-- Name: TABLE tbl_orders_form; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_orders_form TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_orders_form TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_orders_form TO service_role;


--
-- TOC entry 3965 (class 0 OID 0)
-- Dependencies: 301
-- Name: SEQUENCE tbl_orders_form_id_seq; Type: ACL; Schema: test; Owner: postgres
--

GRANT ALL ON SEQUENCE test.tbl_orders_form_id_seq TO anon;
GRANT ALL ON SEQUENCE test.tbl_orders_form_id_seq TO authenticated;
GRANT ALL ON SEQUENCE test.tbl_orders_form_id_seq TO service_role;


--
-- TOC entry 3966 (class 0 OID 0)
-- Dependencies: 302
-- Name: TABLE tbl_production; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_production TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_production TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_production TO service_role;


--
-- TOC entry 3967 (class 0 OID 0)
-- Dependencies: 303
-- Name: SEQUENCE tbl_production_id_seq; Type: ACL; Schema: test; Owner: postgres
--

GRANT ALL ON SEQUENCE test.tbl_production_id_seq TO anon;
GRANT ALL ON SEQUENCE test.tbl_production_id_seq TO authenticated;
GRANT ALL ON SEQUENCE test.tbl_production_id_seq TO service_role;


--
-- TOC entry 3968 (class 0 OID 0)
-- Dependencies: 304
-- Name: TABLE tbl_proofing; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_proofing TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_proofing TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_proofing TO service_role;


--
-- TOC entry 3969 (class 0 OID 0)
-- Dependencies: 305
-- Name: SEQUENCE tbl_proofing_id_seq; Type: ACL; Schema: test; Owner: postgres
--

GRANT ALL ON SEQUENCE test.tbl_proofing_id_seq TO anon;
GRANT ALL ON SEQUENCE test.tbl_proofing_id_seq TO authenticated;
GRANT ALL ON SEQUENCE test.tbl_proofing_id_seq TO service_role;


--
-- TOC entry 3970 (class 0 OID 0)
-- Dependencies: 306
-- Name: TABLE tbl_users; Type: ACL; Schema: test; Owner: postgres
--

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_users TO anon;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_users TO authenticated;
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE test.tbl_users TO service_role;


--
-- TOC entry 2524 (class 826 OID 30134)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: test; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test GRANT ALL ON SEQUENCES TO service_role;


--
-- TOC entry 2527 (class 826 OID 30135)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: test; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA test GRANT ALL ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA test GRANT ALL ON SEQUENCES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA test GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA test GRANT ALL ON SEQUENCES TO service_role;


--
-- TOC entry 2529 (class 826 OID 30136)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: test; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test GRANT ALL ON FUNCTIONS TO service_role;


--
-- TOC entry 2530 (class 826 OID 30137)
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: test; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA test GRANT ALL ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA test GRANT ALL ON FUNCTIONS TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA test GRANT ALL ON FUNCTIONS TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA test GRANT ALL ON FUNCTIONS TO service_role;


--
-- TOC entry 2531 (class 826 OID 30138)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: test; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA test GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


--
-- TOC entry 2533 (class 826 OID 30139)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: test; Owner: supabase_admin
--

ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA test GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA test GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA test GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE supabase_admin IN SCHEMA test GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO service_role;


-- Completed on 2025-01-30 21:36:26

--
-- PostgreSQL database dump complete
--

